config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  #get  '/help',    to: 'static_pages#help'
  #get  '/about',   to: 'static_pages#about'
  #get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/list',     to: 'books#list'
  get '/show',     to: 'books#show'
  get '/new',      to: 'books#new'
# get '/index',    to: 'static_pages#index'
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true, length:{maximum:50}
    validates :author, presence: true, length:{maximum:50}
    validates :publisher, presence: true, length:{maximum:50}
    validates :genre, presence: true, length:{maximum:50}

    def self.search(search) #ここでのself.はBooks. を意味する
      if search
        where(['title LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
      else
        all #全て表示。Book. は省略
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true,   length:{maximum:255},
                format: { with: VALID_EMAIL_REGEX } ,
                uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in_user

    def new
      @book = Book.new
    end

    def edit
      @book = Book.find(params[:id])
    end

    def update
      @book = Book.find(params[:id])
      if @book.update_attributes(book_params)
        flash[:success] = "Book Information Updated"
        redirect_to @book
      else
        render 'edit'
      end
    end

    def create
        @book = Book.new(book_params)
        if @book.save
            flash[:success] = "Success Add New Book"
            redirect_to @book
          else
            render 'new'
        end
    end

    def book_params
      params.require(:book).permit(:title, :author, :publisher, :genre)
    end

    def show
      @book = Book.find(params[:id])
    end

    def list
      @books = Book.paginate(page: params[:page]).search(params[:search])
    end

    def destroy
      Book.find(params[:id]).destroy
      flash[:success] = "Book deleted"
      redirect_to list_path
    end
    private
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
     end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to MM's Book App!"
      redirect_to list_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def logged_in_user
     unless logged_in?
       flash[:danger] = "Please log in."
       redirect_to login_url
     end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    # ページごとの完全なタイトルを返します。
    def full_title(page_title = '')
      base_title = "MM's Book App"
      if page_title.empty?
        base_title
      else
        page_title + " | " + base_title
      end
    end
  end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # 渡されたユーザーでログインする
    def log_in(user)
      session[:user_id] = user.id
      session[:name] = user.name
    end

      # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

# def store_location
#   session[:forwarding_url] = request.original_url if request.get?
# end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<tr>
    <td><%= book.id %> </td>
    <td><%= link_to book.title , book %> </td>
</tr>

app/views/books/edit.html.erb
<% provide(:title, "Book Information") %>
<h1>Update Book Information</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@book) do |f| %>
      <%= render 'shared/book_error_messages' %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>

      <%= f.label :publisher %>
      <%= f.text_field :publisher, class: 'form-control' %>

      <%= f.label :genre %>
      <%= f.text_field :genre, class: 'form-control' %>

      <%= f.submit "Update!", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/books/list.html.erb
<% provide(:title,"Book List") %>
<div class="row">
  <aside class="col-md-4">

    <body>
        <div class="container">

        <h3>Book Search</h3>
        <%= form_tag(list_path, :method => 'get' ) do %>
          <%= text_field_tag :search %>
          <%= submit_tag 'Search', :title => nil %>
        <% end %>

        <%= will_paginate %>
        <table border="1" style="border-collapse: collapse">
        <tr>
            <th>id</th>
            <th>title</th>
        </tr>
        <% @books.each do |book|%>
            <%= render book %>
        <% end %>
        </table>
        <%= will_paginate %>
        </div>
    </body>
  </aside>
</div>

app/views/books/new.html.erb
<% provide(:title, 'Add New Book') %>
<h1>Add New Book</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
      <%= render 'shared/book_error_messages' %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>

      <%= f.label :publisher %>
      <%= f.text_field :publisher, class: 'form-control' %>

      <%= f.label :genre %>
      <%= f.text_field :genre, class: 'form-control' %>

      <%= f.submit "Add New Book", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<% provide(:title,"Add Book Content") %>
  <aside class="col-md-4">
        <body>
            <h1>Add Book Content</h1>
            <div class="container">
                <table border="1" style="border-collapse: collapse">
                    <tr>
                        <th>title</th>
                        <th>author</th>
                        <th>publisher</th>
                        <th>genre</th>
                    </tr>

                    <tr>
                        <td><%= @book.title %> </td>
                        <td><%= @book.author %> </td>
                        <td><%= @book.publisher %> </td>
                        <td><%= @book.genre %> </td>
                        <td>
                        | <%= link_to  "edit" , edit_book_path(@book.id)  %>
                        | <%= link_to "delete", @book, method: :delete,  data: { confirm: "You sure?" } %>
                        </td>
                    </tr>
                </table>
            </div>
        </body>
    </aside>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a>Book App by Michiya Morisaki</a>
  </small>
  <nav>
    <ul>
      <li><a href="https://news.yahoo.co.jp/">Yahoo!News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "MM's Book App", root_path, id: "logo" %>

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li><%= link_to "Home", root_path %></li>
            <li><%=link_to "#{session[:name]}さん",current_user %></li>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application',
                           'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_book_error_messages.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@book.errors.count, "error") %>.
    </div>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
        <% if logged_in? %>
          <h1>Contents</h1><br>
          <h2>
            <li><%= link_to "Book List", list_path %></li><br><br>
            <li><%= link_to "Add New Book", new_path %></li>
          </h2>
        <% else %>
          <h1>Welcome to MM's Book App</h1>

          <h2>
            読みたい本・読んだ本など徒然なるままに
          </h2>
          <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
        <% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= @user.name %>
</h1>